name: Sync Translations with Phrase CLI

on:
  push:
    branches:
      - main  # Adjust based on your needs
  pull_request:
    branches:
      - main  # Adjust based on your needs

jobs:
  phrase-operations:
    runs-on: ubuntu-latest
    container: phrase/phrase-cli:latest  # Use the Phrase CLI Docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Phrase Operations
      run: |
        # Adjusted flag for access token
        phrase push --access_token="${{ secrets.PHRASE_ACCESS_TOKEN }}" --project_id="${{ secrets.PHRASE_PROJECT_ID }}"
      env:
        PHRASE_ACCESS_TOKEN: ${{ secrets.PHRASE_ACCESS_TOKEN }}
        PHRASE_PROJECT_ID: ${{ secrets.PHRASE_PROJECT_ID }}
    
