name: Sync Translations

on:
  push:
    branches:
      - main  # Adjust this to match your primary branch or any branches you want to trigger this workflow
  pull_request:
    branches:
      - main  # Adjust this to match your primary branch

jobs:
  sync-translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Phrase CLI
      run: |
        curl -sL https://github.com/phrase/phrase-cli/releases/latest/download/phrase_linux_amd64.tar.gz | tar xz
        sudo mv phrase_linux_amd64 /usr/local/bin/phrase
    
    - name: Make script executable
      run: chmod +x scripts/phrase-operations.sh

    - name: Run Phrase Operations Script
      run: ./scripts/phrase-operations.sh
      env:
        PHRASE_ACCESS_TOKEN: ${{ secrets.PHRASE_ACCESS_TOKEN }}
        PHRASE_PROJECT_ID: ${{ secrets.PHRASE_PROJECT_ID }}

