name: Sync Translations

on: [push, pull_request]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Prepare Phrase Configuration
      run: |
        sed -i 's/PHRASE_ACCESS_TOKEN_PLACEHOLDER/${{ secrets.PHRASE_ACCESS_TOKEN }}/g' phrase.yml
        sed -i 's/PHRASE_PROJECT_ID_PLACEHOLDER/${{ secrets.PHRASE_PROJECT_ID }}/g' phrase.yml
